# Generated by Django 3.1 on 2020-08-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
                ('college_name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('categogry', models.BooleanField(default=True)),
            ],
        ),
    ]
