# Generated by Django 2.2.4 on 2020-08-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='categogry',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='gender',
        ),
        migrations.AddField(
            model_name='mentor',
            name='category',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
    ]
